### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by dhafitf** [dhafitf/dhafit#16]
## Tasks

- [x] Change layout #17
- [x] Fix vulnerable alert #19 
- [x] Improve SEO #20 
- [x] Create dashboard page #18 
- [x] Add Spotify currently playing widget #17
